### PR TITLE
Feat / Add ISS live tracking component

### PR DESCRIPTION
**Pull request by ss-deep**
- Updated component 2 with a real-time International Space Station tracker.
- Displays the live location of the ISS, updating every 5 seconds.
- Used the Leaflet library for the map.
- Also updated readme with my name :)

image

### CODE REVIEW

**Review by Tayrika — APPROVED** [review]

**Review by r1g023 — CHANGES_REQUESTED** [review]
@ss-deep  

This looks fantastic! I did notice some merge conflicts, likely due to recent updates to the Dev branch. Could you please check out the Dev branch, fetch the latest changes, rebase, and then check out your branch and rebase again to ensure it’s fully up-to-date?  

Currently, the PR Netlify deployment shows the previous footer data and some other elements that have since been updated on the Dev branch. Resolving the conflicts should align everything nicely. Other than that, everything looks great!

**Comment by ss-deep** [comment]
> @ss-deep
> 
> This looks fantastic! I did notice some merge conflicts, likely due to recent updates to the Dev branch. Could you please check out the Dev branch, fetch the latest changes, rebase, and then check out your branch and rebase again to ensure it’s fully up-to-date?
> 
> Currently, the PR Netlify deployment shows the previous footer data and some other elements that have since been updated on the Dev branch. Resolving the conflicts should align everything nicely. Other than that, everything looks great!

Thanks @r1g023, I have resolved the conflicts.

**Review by jucheng925 — APPROVED** [review]
Looks great! Like the fact that you added a shadow!

**Review by PsYk3s — APPROVED** [review]
So cool! well done!

**Review by r1g023 — APPROVED** [review]

**Review by Valeriusdev — APPROVED** [review]

**Pull request merged**
